# Nombre del servicio
spring:
  application:
     name: auth-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
      
server:
  port: 8888
 
# Config propia
app:
  jwtSecretKey: P@tit0
  authUrl: /auth
 